### ISSUE TITLE
Race Condition Found

### ISSUE THREAD

**Issue by ghost** [JuliaParallel/rodinia#1]
I compiled the following 2 source codes

[streamcluster_omp](http://www.cs.virginia.edu/~kw5na/lava/Rodinia/Packages/Current/rodinia_3.0/openmp/streamcluster/streamcluster_omp.cpp)
[streamcluster_original](http://www.cs.virginia.edu/~kw5na/lava/Rodinia/Packages/Current/rodinia_3.0/openmp/streamcluster/streamcluster_original.cpp)

I run the executables.
`./stream_cluster_omp 10 20 32 4096 4096 1000 none output_small.txt.serial 1`
`./stream_cluster_original 10 20 32 4096 4096 1000 none output_small.txt.parallel 12`

I compared the output files using `diff output_small.txt.parallel output_small.txt.serial`

**The results were different**

Please note that this bug is independent of the number of threads used.

**Comment by maleadt** [comment]
Sorry for the late response. We don't maintain Rodinia here, just a fork focused on Julia implementations. You better contact [upstream](lava.cs.virginia.edu/wiki/rodinia) to get this fixed.
