### ISSUE TITLE
mummer gpu on v100

### ISSUE THREAD

**Issue by harisankarsadasivan** [JuliaParallel/rodinia#2]
Observing long reads of 9kb is 1.2x slower than an equivalent total basepair version of short reads on GPU dataset while 18kb long read dataset is 1.83x slower than its equivalent short read dataset. We figured out that V100 has much higher l1 and l2 caches than 8800. Is there any parameter that we could change to optimize mummergpu for longer reads on the powerful v100?

**Comment by maleadt** [comment]
This repo is the fork of Rodinia that focuses on Julia ports, and there's no Julia port of the mummer benchmark. I don't maintain these benchmarks, so I recommend you refer to the original authors: https://rodinia.cs.virginia.edu/doku.php
